item {
  id: 1
  name: 'mangifera indica'
}

item {
  id: 2
  name: 'rubus niveus'
}
item {
  id: 3
  name: 'caesalpinia decapetala'
}
item {
  id: 4
  name: 'psidium guajava'
}
item {
  id: 5
  name: 'eriobotrya japonica'
}
item {
  id: 6
  name: 'garcinia livingstonei'
}
item {
  id: 7
  name: 'monodora myristica'
}

item {
  id: 8
  name: 'ricinus communis'
}
item {
  id: 9
  name: 'tithonia diversifolia'
}

